# -*- coding: utf-8 -*-
"""week1.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1n81N_9J2gei4tDrTYmPJGXCWymJ3Zp-g
"""

var1 = 15
var2 = "cuma"
gun = "cuma"
var3 = 10.6454
list_int = [1,2,3,4,5]
a = [1,2,3,4,5]
type(a)
type(var2)
type(var1)

list_str=["pazartesi","salı","carsamba", "persembe", "cuma", "cumartesi", "pazar"]
list_int=[1,2,3,4,5,6]
value = list_int[0] 
print(value)
print(list_int[5])
print(list_str[1:5])
dir(list_int)
#help(help)
list_int.remove(1)
list_int.reverse()
list_str.remove("pazar")
print(list_str)
list_str.append("pazar")
print(list_str)
print(list_int) 
new_list = [9, 5, 11 ,1, 3 , 7, 95, 7, 66, 41]
new_list.sort()
print(new_list)
sum(list_int)

min = 100000
liste = [5,1,4,7,8,5,88,99,77,44,66]
for each in liste:
  if(each < min):
     min = each
print(min)

var1 = 10
var2 = 20
if(var1 > var2):
  print("var1 > var2")
elif(var2 > var1):
  print("var2 > var1")
else:
  print("var1 ve var2 eşittir")

liste =[1,2,3,4,5]

value = 3

if value in liste:
    
    print("value değeri {} listenin içindedir.".format(value))
    
else:
    print("value değeri {} listenin içinde değildir.".format(value))

sayi = 1
while(sayi<10):
  print(sayi)
  sayi = sayi+1

"""LAMBDA VE NORMAL FONKSİYON KULLANIMI"""

def cember_cevre(r):
   output =  2*r*3.14
   return output
cember_cevre(2)

cember_cevre2 = lambda x : 2*x*3.14
cember_cevre2(5)

"""DICTIONARY"""

dic1 = {"elma":10, "armut:":20, "kivi":30}
dic1["elma"]
type(dic1)
dic1.keys()
dic1.values()
dic2 = {"ömer":1, "ahmet":2, "mehmet":3}
keys = dic2.keys()
if "ömer" in keys:
  print("yes")
else:
  print("no")